#!/usr/bin/env node
/**
 * Concatenate the harness sources into a single self-contained ESM file.
 *
 * No bundler: the three source modules share one module scope by construction,
 * so the build only has to strip their per-file import/export statements, emit
 * one set of node: imports at the top, and append the public export.
 *
 * The output is verified with `node --check` and a real dynamic import.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const srcDir = path.join(repoRoot, "src", "harness");
const outDir = path.join(repoRoot, "dist");
const outFile = path.join(outDir, "grok-harness.js");

/** Source order matters: later files reference earlier declarations at runtime. */
const SOURCES = ["paths.js", "transcript.js", "hooks.js", "adapter.js"];
const ALLOWED_MODULES = new Set([
  "node:fs",
  "node:fs/promises",
  "node:path",
  "node:os",
  "node:crypto",
]);

/**
 * Remove import/export statements (single- and multi-line) from a module body,
 * collecting the node: imports it declared.
 */
function stripModuleSyntax(source, file, imports) {
  const lines = source.split("\n");
  const kept = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (/^import\b/.test(trimmed)) {
      const statement = [];
      let j = i;
      while (j < lines.length) {
        statement.push(lines[j]);
        if (/;\s*$/.test(lines[j])) break;
        j++;
      }
      const text = statement.join("\n");
      const specifier = /from\s+"([^"]+)"/.exec(text)?.[1] ?? "";
      if (specifier.startsWith(".")) {
        // Intra-bundle import: dropped, the declarations are already in scope.
      } else if (ALLOWED_MODULES.has(specifier)) {
        const binding = /^import\s+([A-Za-z_$][\w$]*)\s+from/.exec(text)?.[1];
        if (!binding) {
          throw new Error(
            `${file}: only default imports of node: builtins are supported, got:\n${text}`,
          );
        }
        const existing = imports.get(specifier);
        if (existing && existing !== binding) {
          throw new Error(
            `${file}: ${specifier} is imported as both "${existing}" and "${binding}"`,
          );
        }
        imports.set(specifier, binding);
      } else {
        throw new Error(`${file}: disallowed import "${specifier}"`);
      }
      i = j;
      continue;
    }

    if (/^export\s*\{/.test(trimmed)) {
      let j = i;
      while (j < lines.length && !/;\s*$/.test(lines[j])) j++;
      i = j;
      continue;
    }

    if (/^export\s+(const|let|function|class|async)\b/.test(trimmed)) {
      kept.push(line.replace(/^(\s*)export\s+/, "$1"));
      continue;
    }

    if (/^export\b/.test(trimmed)) {
      throw new Error(`${file}: unsupported export form: ${trimmed}`);
    }

    kept.push(line);
  }
  return kept.join("\n").replace(/^\n+/, "").replace(/\n+$/, "");
}

/** Top-level declaration names, so collisions fail the build loudly. */
function declaredNames(body) {
  const names = new Set();
  const pattern = /^(?:const|let|var|function|class|async function)\s+([A-Za-z_$][\w$]*)/gm;
  let match;
  while ((match = pattern.exec(body)) !== null) names.add(match[1]);
  return names;
}

async function build() {
  const imports = new Map();
  const chunks = [];
  const seen = new Map();

  for (const file of SOURCES) {
    const source = await fs.readFile(path.join(srcDir, file), "utf-8");
    const body = stripModuleSyntax(source, file, imports);
    for (const name of declaredNames(body)) {
      const owner = seen.get(name);
      if (owner) {
        throw new Error(`name collision: "${name}" is declared in both ${owner} and ${file}`);
      }
      seen.set(name, file);
    }
    chunks.push(`// ---------------------------------------------------------------------------
// src/harness/${file}
// ---------------------------------------------------------------------------

${body}`);
  }

  const importLines = [...ALLOWED_MODULES]
    .filter((specifier) => imports.has(specifier))
    .map((specifier) => `import ${imports.get(specifier)} from "${specifier}";`);

  const output = `// Generated by scripts/build-harness.js -- do not edit.
// Self-contained squab harness + session adapter for xAI's Grok Build CLI.

${importLines.join("\n")}

${chunks.join("\n\n")}

export { registerGrok };
`;

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(outFile, output);
  return output;
}

async function verify() {
  const { execFile } = await import("node:child_process");
  const { promisify } = await import("node:util");
  await promisify(execFile)(process.execPath, ["--check", outFile]);

  const module = await import(`${pathToFileURL(outFile).href}?t=${Date.now()}`);
  if (typeof module.registerGrok !== "function") {
    throw new Error("built module does not export registerGrok");
  }
  const calls = [];
  module.registerGrok(
    (adapter) => calls.push(["adapter", adapter.agent]),
    (def) => calls.push(["harness", def.agentName]),
  );
  const shape = JSON.stringify(calls);
  if (shape !== '[["harness","grok"],["adapter","grok"]]') {
    throw new Error(`unexpected registration sequence: ${shape}`);
  }
}

const output = await build();
await verify();
process.stdout.write(
  `built ${path.relative(repoRoot, outFile)} (${output.length} bytes) and verified it loads\n`,
);
